# Generated by Django 5.2.9 on 2026-01-01 19:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gee_id', models.CharField(max_length=50, unique=True)),
                ('zone_type', models.IntegerField(help_text='Coffee presence probability from GEE', null=True)),
                ('pixel_count', models.IntegerField(null=True)),
                ('region_name', models.CharField(blank=True, max_length=100)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236)),
            ],
        ),
    ]
