# Generated by Django 5.2.9 on 2026-01-02 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_district'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT UpdateGeometrySRID('map_coffeezone', 'mpoly', 4326);"
        ),
        migrations.AlterField(
            model_name='coffeezone',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
